name: run scraper.py

on:
  schedule:
    # Runs at 08:00 UTC every Sunday
    - cron: '0 8 * * 0'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  scrape_and_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python scraper.py

      - name: commit database updates
        run: |
          git config --local user.email "wyu31@github.com"
          git config --local user.name "Local Activities GitHub Action"
          # Ensure the local branch is up-to-date with the remote branch
          git pull --rebase
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Updated local activities database with new entries" && (git push || (echo "Push failed, retrying..." && git pull --rebase && git push)))
  