name: run scraper.py

on:
  schedule:
    # Runs at 08:00 UTC every Sunday
    - cron: '0 8 * * 0'

jobs:
  scrape_and_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Ensure this matches the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          # Include any other dependencies you might need

      - name: Run script
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add -A
          git commit -m "Update events and forecasts"
          git push